name = "ovp"
main = "src/index.ts"
compatibility_date = "2023-08-21"

[[d1_databases]]
binding = "ovp"
database_name = "ovp"
database_id = "fcb2f6da-ef2a-4b63-a75e-6df1604229a0"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "zealy"
id = "b7d1143b485640bbaaaaf70160876f2e"
preview_id = "328d2f45434f416bb713f931646ac2a4"